name: ConnectionLimiter
main: com.lucatm11.connectionlimiter.ConnectionLimiter
version: B7
commands:
  connectionlimiter:
    description: Main command.
permissions:
  connectionlimiter.help:
    description: Allows the player to view the help screen.
  connectionlimiter.checkconnections:
    description: Allows the player to check the active connections of another player.
  connectionlimiter.reload:
    description: Allows the player to reload the configuration file of the plugin.
  connectionlimiter.exempt:
    description: Lets the player join the server even if the limit of simultaneous connections has been reached.
  connectionlimiter.notify:
    description: Notify the player if a player reached the limit of simultaneous connections and attempted to join.