name: ConnectionLimiter
main: com.lucatm11.connectionlimiter.ConnectionLimiter
version: B6
commands:
  connectionlimiter:
    description: Main command.
permissions:
  connectionlimiter.help:
    description: Allows the player to view the help screen.
  connectionlimiter.checkconnections:
    description: Allows the player to check the active connections of another player.
  connectionlimiter.reload:
    description: Allows the player to reload the configuration file of the plugin.
  connectionlimiter.bypass:
    description: Lets the player join the server even if the limit of simultaneous connections has been reached.